//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartAGSolutionApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SmartAGSolutionApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air humidty:.
        /// </summary>
        public static string Air_humidity {
            get {
                return ResourceManager.GetString("Air_humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air temperature:.
        /// </summary>
        public static string Air_temperature {
            get {
                return ResourceManager.GetString("Air_temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear cached files.
        /// </summary>
        public static string Clear_cached_files {
            get {
                return ResourceManager.GetString("Clear_cached_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the button to get latest measurements.
        /// </summary>
        public static string Click_on_the_button_to_get_latest_measurements {
            get {
                return ResourceManager.GetString("Click_on_the_button_to_get_latest_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click on the button to list latest measurements.
        /// </summary>
        public static string Click_on_the_button_to_list_latest_measurements {
            get {
                return ResourceManager.GetString("Click_on_the_button_to_list_latest_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CO2:.
        /// </summary>
        public static string CO2 {
            get {
                return ResourceManager.GetString("CO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description:.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter description.
        /// </summary>
        public static string Enter_description {
            get {
                return ResourceManager.GetString("Enter_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter greenhouse name.
        /// </summary>
        public static string Enter_greenhouse_name {
            get {
                return ResourceManager.GetString("Enter_greenhouse_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter greenhouse phone number.
        /// </summary>
        public static string Enter_greenhouse_phone_number {
            get {
                return ResourceManager.GetString("Enter_greenhouse_phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Latest Measurements.
        /// </summary>
        public static string Get_latest_measurements {
            get {
                return ResourceManager.GetString("Get_latest_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse profile.
        /// </summary>
        public static string Greenhouse_profile {
            get {
                return ResourceManager.GetString("Greenhouse_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse profile is not selected.
        /// </summary>
        public static string Greenhouse_profile_is_not_selected {
            get {
                return ResourceManager.GetString("Greenhouse_profile_is_not_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greenhouse profile with similar name already exists..
        /// </summary>
        public static string Greenhouse_profile_with_similar_name_already_exists {
            get {
                return ResourceManager.GetString("Greenhouse_profile_with_similar_name_already_exists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity:.
        /// </summary>
        public static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illuminance:.
        /// </summary>
        public static string Illuminance {
            get {
                return ResourceManager.GetString("Illuminance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List Latest Measurements.
        /// </summary>
        public static string List_latest_Measurements {
            get {
                return ResourceManager.GetString("List_latest_Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements.
        /// </summary>
        public static string Measurements {
            get {
                return ResourceManager.GetString("Measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurements overview.
        /// </summary>
        public static string Measurements_overview {
            get {
                return ResourceManager.GetString("Measurements_overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modify.
        /// </summary>
        public static string Modify {
            get {
                return ResourceManager.GetString("Modify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name or phone number field cannot be emtpy..
        /// </summary>
        public static string Name_or_phone_number_field_cannot_be_emtpy {
            get {
                return ResourceManager.GetString("Name_or_phone_number_field_cannot_be_emtpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number:.
        /// </summary>
        public static string Phone_number {
            get {
                return ResourceManager.GetString("Phone_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select greenhouse profile.
        /// </summary>
        public static string Select_greenhouse_profile {
            get {
                return ResourceManager.GetString("Select_greenhouse_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Smart AG Solution.
        /// </summary>
        public static string Smart_AG_Solution {
            get {
                return ResourceManager.GetString("Smart_AG_Solution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature:.
        /// </summary>
        public static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This operation will delete all profiles and history of measurements. Are you sure you want to continue?.
        /// </summary>
        public static string This_operation_will_delete_all_profiles_and_history_of_measurements {
            get {
                return ResourceManager.GetString("This_operation_will_delete_all_profiles_and_history_of_measurements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
